<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "bs_text_classification"
 *
 * Auto generated by Extension Builder 2017-04-03
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'TextClassification Module',
	'description' => 'Classifies different articles with different algorithms',
	'category' => 'plugin',
	'author' => 'Barbara Sikora',
	'author_email' => 'barbara-sikora@gmx.at',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'extbase' => '7.6.0',
			'fluid' => '7.6.0',
			'typo3' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);